# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Z8dwndBKCUcuhkFyO6Itguja3EDHD0n1Rcfv2a6XH2JUumyMl39wqQ==,iv:Fr43iiSS0JxXYR1bKRheGLXwjYpGvHylYASGB/3279E=,tag:ovP295T5KXiaNMyfqCea6w==,type:str]
sops:
  age:
    - recipient: age1x3l0v6l2mcy0e56gyds3kteh0ngprw0cg8psqjtcza7jym4d893qazvdjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbUNaVnJqM1NDdXZLTUpt
        ckVQWFg1WlJRMExoVHRweVVHQWw1R1lnTkVvCkdTTmhVeUVCbWJ6b2VBUVM0cVk5
        VlpJQXdBNXVnZTlTcGNmcGdHdnhDa2MKLS0tIFdhUXRTYXdEOUVJdmRYNEl6RkdT
        UVJCTFI3OXl3OVFZRDhzQmlhVWx2RHcK9nSFJd4dxQLXyXaXppU8o/A5Kptdz7oK
        d8KO0QATLdPaHk0Wwodk3KL029LU6dZQ9O9gZyvdPgtc2oj6f80DJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-06T09:37:57Z"
  mac: ENC[AES256_GCM,data:CIYw/9FzFeP8qaZG2zTGhi+AgDMRE6E+cdnzjkvbb0jpAh+XFL+zWpcCrsakle0XMdJGbWneUtOJxpKD3a+hswF/xRWSaL0RkX+Y3HtIiXZ4MIaKGR7t1YlnPPXJ8/iy58QvXbwWaZ/lupT2vs2UcJa324yMpiIPgj/e6+Dbl5c=,iv:DuWhU7MxgsisZVipm/chYxHWNgRjOwLXiRQbN0PhzgY=,tag:DKDIxp6NCZMipSF1kgvW6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
