---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
# configMapGenerator:
#   - name: nvidia-values
#     files:
#       - values.yaml=./helm/values.yaml
# configurations:
#   - ./helm/kustomizeconfig.yaml
