# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:0CFFgpI2GzE48CxDiaSQrqEWOSfCfRyf7Vsw1tF8AYs=,iv:ALT7NEKZmifu94cnNcdbWP4gLlA7opWB/75yyLuyTXY=,tag:b0p7z3VfYIfW3gFxPDCSEA==,type:str]
sops:
  age:
    - recipient: age1x3l0v6l2mcy0e56gyds3kteh0ngprw0cg8psqjtcza7jym4d893qazvdjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUXBHOTNlSUlvWlRnTDk3
        ZW9LQUY3VnV4U3dxTHBoZmVoVzlTYUFJNHpvClhhSVAydFhaL2ZGR2s2SStxM0VQ
        bG5naUl5bVJ3YjlFTUJxdHpkZEorYlkKLS0tIFQrOEdIOHA2THNiVmp2Qmw4bEVC
        U1p2dTZqVGRueDZNS2VMRXpzdTdZaXMKO1CNE6l4Y5Hk7sLoekYI1feyYLgUlmE5
        LcSuWmAYuLOe0bJdcU17P527HTxmkNMwTCq50+SgjhsbaNnR2nZYEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-06T09:37:57Z"
  mac: ENC[AES256_GCM,data:Rw/GV4bSEqoXoM+rRboRzU8QEwNEvsihLFBx8Muc422Basp3QZKmNn5QM03lPwkj5nJwewQEcspIGo3B8gOvt6Hnd6W2Vcb0aj/uT79W7ZGcuq2K3Ty8yX6G4Fyc/MkWM9IYcEM8DvvcVoqg4yYy9ZGq5h/YPlyi1UvKbwb3I4w=,iv:L4ALQIU9pBkTpYRYI7gDp+Dz19kEdOK49fqog8b3M5Y=,tag:gW0fjgXts/b4zxmsfdeYuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
