# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ksNhtxhqVuPkwcpb5IqCL8NGTJbR6YXsGrLrY1nFf4aPMADC7N24Fw==,iv:U/OsiUe/YKo2FagHGiUzGnIQpw5vjqr98zSgbmW4/CE=,tag:z2Xdlg8qj1U3uwfkLO81Yg==,type:str]
sops:
  age:
    - recipient: age1x3l0v6l2mcy0e56gyds3kteh0ngprw0cg8psqjtcza7jym4d893qazvdjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRkh0c1ZtbnlvdXUxUUFY
        NFJHdlV3UXVKcE5RbnJVd0h0VWdhN000aUE4CmFyNkw5ZGVXU2ZIa2NpTDFIQWNy
        a3lMeStwY3VzTHU5ODM2VThIZDJXNzAKLS0tIDdHODZQc2d4OWt6YlNjbHVSTnJq
        R2Z6MHZLeFJuZEVPWGsycjNOaklRV28KFALrNkIqm3qTzLcRwEPjjZVGSEbZlEMc
        1fRFiE5eIEqsQfCv7qr92nDd29Mb2N/1jsk/Wg7kak+5Y+oKCf/hzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-06T09:37:57Z"
  mac: ENC[AES256_GCM,data:jMm50c5QYaTE2mvGtWqI+tfrZM6jYhzBNB5Iigmaru6OZ+6AJ/vlIXJdcGaTD4X8xK2ReZyshCzl+ZSiD/9dsot4SMQexkrOczNp3o0AUQu8Q58ae+CGDZGuAYFgKnsPKhH5om3YYEH2hRe+NWsTSvMb6MJyuSSHu6+wnqAR2fE=,iv:5zK+PbSXlXT/zEjCik6q0ZvsPGCZAOUt6W9zS4kRoVQ=,tag:1i5iN3y3LgDT/Xznk0UMrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
