# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cQm6rudoujS5EBW6WJkY9Flwf6x3j1DjfUtw01R3OqCF+qZd4om3rA==,iv:U0ydYMvbTWBNN9HQeT49mQqq+iIWj2QETKnSaocbEOE=,tag:De/5KRqfUWKJ4U/F92R/eg==,type:str]
sops:
  age:
    - recipient: age1x3l0v6l2mcy0e56gyds3kteh0ngprw0cg8psqjtcza7jym4d893qazvdjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdWZkMjBJRm9BME01NXQ1
        YzJVU1lYYnN5QUlHY1lWa3MydUwrVk9kaXhNClZVQlp3RGtRaVU0dG4vcVUvNFI3
        czNGdWFvZEIzd2kzQWcwR2hUNmJpZFkKLS0tIG10Z0oybEhNeEcvUWwrdnpBVEE4
        UEN3SWFVTXBNNE9OZnJUVkgzUmNVOVUKoNAVLSDDIrVuFQ7N/rByhdmL/aEn/wM3
        CyJ4pahjx0b8IY28uOLSx0DcYr3xlyvdQTTmY+EusntdkN6x5wrfeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T21:08:37Z"
  mac: ENC[AES256_GCM,data:sVPPjoTeB2Kq26eUjP2X0JIm+D/cwovNJLX9pG3OHlczB87co9CDZAgxYsDQTfnttHsuWtDQNswPqTLrNXJhSic4MGVxQ9qkJuXPPs6dXlV5p7k5xuRm4fhFBHX5tkCdyF1PQ1dK2zbceTIaltGI5mg24f09Zf8h6HELagA7W48=,iv:ORedlnE9OFJ2z4c8gHZ1+Lj1LZcVX5P3KGTFdM33RZc=,tag:sW6yXDWZJHYLWfsd9u+U2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
